[package]
name = "example"
version = "0.1.0"
authors = ["Philipp Eder <philipp.eder@greenbone.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lexer = { path = "../lexer" }
