[package]
name = "nasl"
version = "0.1.0"
authors = ["Philipp Eder <philipp.eder@posteo.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
